export const colorVariants: Record<string, string> = {
  accentRed: 'border-accentRed',
  accentGreen: 'border-accentGreen',
  accentOrange: 'border-accentOrange',
  accentBlue: 'border-accentBlue',
  accentYellow: 'border-accentYellow',
  accentPink: 'border-accentPink',
  accentPurple: 'border-accentPurple',
  accentCyan: 'border-accentCyan',
  accentLime: 'border-accentLime',
  accentTeal: 'border-accentTeal',
  accentBrown: 'border-accentBrown',
  accentIndigo: 'border-accentIndigo',
  accentGold: 'border-accentGold',
  accentMagenta: 'border-accentMagenta',
  accentKhaki: 'border-accentKhaki',
  accentNavy: 'border-accentNavy',
  accentTan: 'border-accentTan',
  accentSilver: 'border-accentSilver',
  accentCrimson: 'border-accentCrimson',
  accentOlive: 'border-accentOlive',
  accentAqua: 'border-accentAqua',
  disabled: 'border-white bg-logoTheme',
};
